### ISSUE TITLE
PostGIS filesystem

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#107]
# Steps for setting up PostGIS filesystem
- [x] 1. Docker PostGIS db
- [x] 2. More robust uploader
- [x] 3. Create API endpoints and processing functions
- [x] 4. New filesystem for data based on PostGIS
# 
### 1. Docker PostGIS database
- [x] Create docker container with latest Postgres and PostGIS (from `Dockerfile`), [this is a good Dockerfile](https://github.com/helmi03/docker-postgis).
- [x] Create a separate `data container` for PostGIS, so all data is stored in a pluggable data container.
- [x] Enable PostGIS extensions, create user, table on PostGIS database (if not exists) on `docker build`
- [x] Add PostGIS container to `docker-compose.yml` [docker-systemapic](https://github.com/systemapic/docker-systemapic) composition.
- [x] [Tune](http://pgtune.leopard.in.ua/) and enable all kinds of [spatial functions](https://github.com/CartoDB/cartodb-postgresql/wiki) 
### 2. Robust Uploader
- [ ] Separate API endpoint for `data` uploads and `image/doc/pdf` uploads, and separate flows in client.
- [ ] Support direct connection with PostGIS for importing tables.
- [x] Create separate `PostGIS database` for each user, and `table` for each data file.
- [x] Support `zip`, `tar` archives
- [x] Oauth2 `access_token` based authenication
- [x] To make life easier, enough to support one file upload at a time (ie. one shapefile per zip, etc.)
- [ ] Comprehensive error checks, catch invalid files.
- [x] Register files/dataset as MongoDB `file` model objects.
- [x] Return full information about upload back to client on successful upload.
- [ ] Documentation of endpoints `/api/data/upload` and `/api/data/upload/chunked`.
- [ ] Clean-up and delete old routes.
##### Resumable (later)
- [x] Support chunked uploading with [Resumable.js](resumablejs.com)
- [ ] Check headers of data-files (first chunk) for metadata: type of file, other metadata. Enable first/last chunk upload in Resumable.js. Check beginning of file in normal upload. Send back with sockets to `systemapic.js` client, notify in other way with other clients (perhaps do a GET request to an endpoint). Can also check `.zip` files for content by reading last chunk.
- [x] Resumable chunks that are already uploaded sometimes don't start processing due to wrong redis-count, fix.
- [x] Delete chunks after succesful upload.
### 3. Error checks
- [x] Feedback for not accepted files
- [x] Feedback for error in files
### 4. PostGIS API Endpoints

See #153 and #151 
#### Features

All requests to `/api/db/*` are proxied to `pile`. All _export_ of postgis data (ie. tiles, geojson, files, tables) go from `pile`, incl. manipulating of data, etc.
- [ ] Create endpoints in [PostGIS Tile Server API](https://github.com/systemapic/pile) for: 
  - [ ] getting geojson, shapefile from PostGIS data
  - [x] getting vector tile from PostGIS data
  - [x] getting raster tiles from PostGIS data + CartoCSS
  - [ ] doing processing on vectors
  - [ ] doing processing on rasters
  - [x] doing advanced `SQL queries` on data
  - [ ] exporting data to external PostGIS database
  - [ ] updating data
  - [ ] deleting data
  - [ ] creating new tables (datasets) from `SQL` queries
  - ... etc. 
- [ ] Create db maintenance scripts for PostGIS (to be used by admins)
- [ ] Write tests for all endpoints.
#### Endpoints, `pile`:

All requests must contain `access_token`, either as `body` in POST requests, or `query param` in GET requests.  
- [ ] **`/api/db/getData`**: get postgis data represented as a file or table.  
  **Method:** GET  
  **Options:** `layerUuid`, desired `format` (eg. Shapefile, GeoJSON, table)  
  **Returns:** A file.
- [x] **`/api/db/vector`**: get a vector tile from postgis  
  **Method:** GET  
  **Options:** `layerUuid`, `z`, `x`, `y`.  
  **Returns:** A vector tile (`.pbf`)
- [x] **`/api/db/raster`**: get a raster tile from postgis  
  **Method:** GET  
  **Options:** `layerUuid`, `z`, `x`, `y`.  
  **Returns:** A raster tile (`.png`)
- [x] **`/api/db/createLayer`**: create a layer from postgis data  
  **Method:** POST  
  **Options:** `layerJSON` see #151  
  **Returns:** A `layerUuid`
- [x] **`/api/db/getLayer`**: get stored layer from layerUuid  
  **Method:** GET  
  **Options:** `layerUuid`  
  **Returns:** A layer-object
#### Endpoints, `wu`:
- [ ] `/api/file/get`: get a file object from a `fileUuid`
### 4. File system

For **normal** files (images, docs, etc.), we'll use simple files. For **data based files** (geodata), we'll import to PostGIS. 
- [x] The dataset (`table`) in PostGIS is represented in the MongoDB `file` model.
- [ ] The layers created from the dataset are represented in the MongoDB `layer` model.
- [x] Create a `database` in PostGIS for all new `user`'s.
#### References:
- https://blog.openshift.com/get-more-spatial-in-your-database-with-postgis-21-on-openshift/
