### ISSUE TITLE
Distributed containers

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#223]
#### Todo
- [ ] separate API more between `wu`, `pile`
- [ ] put all heavy processing on `pile`
- [ ] any container can query any other container (wu, pile, postgis, etc.)
#### References:

https://stackoverflow.com/questions/25324860/how-to-create-a-bidirectional-link-between-containers
