### ISSUE TITLE
End of Year Roadmap

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#230]
Shit to do before 2016.
## MVP

do this first! get a beta out!
- [x]  screenshot bug: layers that are active on load are not removed when screenshotting
- [x] css bugs #238 
- [x] fix polygon styler
  - [x] add styling for text column
  - [x] bug: eg. countries in Africa shp doesn't show up in tooltip
  - [x] fix so that it's possible to click on grid when editing style
  - [x] å overstyre `marker-fill` funker ikke på points når range er aktiv og column er targeted.
- [x] change slug on rename
- [x] fix left pane
  - [x] invite flow
  - [x] improve styling
- [x] improve design on styler tabs
- [x] dropdown for base layers
- [x] automatically add (or ask) to add layer after upload
- [x] share datasets with other users
- [x] contact list
- [x] check memory leaks
- [x] bugtest
- [x] new login page + forgot password + privacy policy
- [x] invite by link
- [x] missing description box on screenshots
- [x] decrease to 15 steps in cartocss - big difference in rendering time
#### bugs
- [ ] data filter slider (`mvel`)
##### TODO:
- [ ] check all access server side also
- [x] add user that invited to contact list
- [x] create contact list on user
- [x] add account button
- [x] remove self from contact list
- [x] add logo box to header menu
- [x] update main login page
#### 1. Permissions.
- [ ]  invited users should get a small amount of storage
- [ ] account page with amount of storage used, create `access_token`, name, password, datasets
- [ ] clean up permissions completely. 
- [ ] add storage limits to permissions, 
- [ ] create verticals of storage
- [x] create permission for being able to share project publicly, privately (also as a vertical)
- [x] Separate PORTAL permissions (create_project, create_client, upload_file, create_user) from PROJECT permissions (edit_project, download_file, etc)
- [ ] remove all `roles`
- [ ] clean up all access
#### 2. Browser client v.2
- [x] Finish left pane, users, projects
- [x] Add missing functionality in styler (polygon columns, etc.)
- [x] Enlarge design, make simpler, bigger, more user friendly
#### 3. Client Model
- [x] Remove from errywhere
- [x] Remove from client-side
- [x] Remove from server-side
- [x] Remove from permissions
#### 4. Layer Model
- [ ] clean up layers. make it simpler.
- [ ] see if we can remove one of the layers (wu/pile), or at least sync them automatically.
- [ ] clean up code - it's all over the place. 
- [ ] organize better types of layers (vector, raster, postgis (they're all postgis!), providers, etc.)
- [ ] make ready for raster layers a la frano (ie. with timeseries, aka. layergroups?, etc.), different types of rasters (vectorized, overlays), etc.
- [ ] make ready for vector tiles
- [ ] add extra address - which container db is in - for swarm.
#### 5. API
- [ ] Summer of API #153 
- [ ] Create and SQL API
- [ ] Create a Data API (upload, download).. perhaps merge with SQL
- [ ] Create a Systemapic API (users, account, projects, etc.)
- [ ] make all calls cleanly to the API - ie. doesn't matter if systemapic.js client does it, or cUrl or anything else.
#### 6. Login/Account/Invite
- [ ] Create username and use this for PostGIS database, authentication, etc (instead of email)
- [x] Improve login-flow: bigger design, faster, clearer. 
- [x] Implement cookies (so user won't have to log in again, even after days, on same machine)
- [x] Rethink `access_tokens`: when should they be created, etc.
- [ ] Make possible to create `access_tokens` on account page (both private and public.. understand difference)
- [x] show permissions in invite link (for frano).. or think about how to do this..
- [x] invite users directly in the portal (ie. just add them to a project)
- [x] make project url's like: `dev.systemapic.com/username/project`
#### 6. Cleanup
- [x] Remove old code from client/server
- [x] Document and organize code, client/server
#### 7. Swarm
- [ ] set up containers so that they can receive connections from anywhere:
  - [ ] pile
  - [ ] wu, webserver
  - [ ] postgis, etc.
- [ ] put errything on swarm :)
#### 8. Others
- [ ] accept `.kmz`, `.gpx` etc formats
- [ ] add length of lines to meta info
#### Plans
- everything sockets, live, flowing. you pay, socket pings platform, unlocks. chat, sharing, data updates.
