### ISSUE TITLE
Roadmap: bugs and missing features

### ISSUE THREAD

**Issue by jorgenevil** [systemapic/wu#242]
**What is important to fix _now_, and what can wait till we earn money?**

_As a sidenote, I think it’s important to think modular. Yes, we’re setting up a streamlined process/package, but I think it would be nice to see Systemapic more as a puzzle. Remember, most GIS houses are packed with programmers, and if they can build their own Systemapic portal, powered by the cloud, it would be more competitive._
### DIV
- [ ] **Remove histogram from file object:** Too much clutter. Request each time instead, store locally on client.
- [x] **GEO Search:** needs styling
- [ ] **Uploading:** Hvis man laster opp en fil, sletter den, og laster den opp igjen, må man reloade.
- [ ] **Z-index:** Nå havner lag oppå hverandre i forhold til når de aktiveres. Kanskje det hadde vært en idé å ha dem i rekkefølgen de ligger i lagmenyen? Man vet som regel hva man vil ha øverst (f.eks. labels).
- [ ] **Background:** Det hadde vært fint å sette en solid bakgrunnsfarge til kart – f.eks. hvis man laster opp orto-foto selv, eller lager et område over kun ett land.
- [ ] **Draw-on-map:** vi har vel strengt tatt dette nesten klart. Men dette er et punkt nesten alle vi har snakket med nevner. see #254 
- [ ] **Legend on print:** need to lay out all legend on screenshot.
### TOP MENU (inc left chrome)
- [ ] **Projects & Users:** Perhaps give it a name and a suitable icon, like the rest?
- [ ] **DATA:** I don't think moving layers over to layer menu is our top priority, but if it's not too much work, it's alright.
- [ ] **CartoCSS:** overflow hell – why does this happen all the time?
- [ ] **Extras:** Write this more as plugins.
- [ ] **Options:** Should be able to disable layer menu all together (but to keep layers there, naturally)
  #### _Style_
- [ ] `<` `=` `>` is only interesting if we are dealing with numbers. Is it possible to fetch what kind of data that goes into the postgis column? (string, int, etc)
- [ ] **Blend mode:** Cool!! Need this on polygons as well.
- [ ] **Color range etc.:** When clicking the numbers, the histogram should appear. (Now we end up jumping back and forth to "filters" to see the histogram). Perhaps write histogram as an external function, that can be called in different places?
- [ ] **Lines:** No need to have the same variables here as with polygons and points. I suggest we only deal with fixed values. (I cannot think of any situations where the border of things will need to be "randomized"). It's more interesting in having the ability to make lines dotted or dashed.
- [ ] **Labels:** high priority. But this comes with layers.
- [ ] **Layers:** This is very important the way I see it. With it, we can start styling maps for reals – but this is Sandro's domain (see https://github.com/systemapic/wu/issues/246)
- [ ] **Ghost** on color range disabled? FIX.
- [ ] **Comp-op** on polygons and lines as well.
- [ ] **Publish/preview/render etc:** fix so that users don't fuck around with published layers. (https://github.com/systemapic/wu/issues/261)
- [ ] **Popup:** option to disable pop-up all together for given layer.
- [ ] **Popup:** Fix moment!
### POPUP
- [ ] **Time-series:** Moment picks out a lot of random information that it reads as time (basically anything with a number in it). We need to fix this, so that only time gets into the time series.
- [ ] **Many layers:** Hvis det er mange lag oppå hverandre, blir det mange pop-ups. Tenker som du sier Knut, at dette krever en del omskriving (med DC'etc). Vi bør kanskje skille standard pop-ups fra tidsserie pop-ups totalt, og ha pop-up på point click hvor det er naturlig. Vi bør også ha mulighet til å velge om et lag skal ha pop-up i det heletatt – det er ofte dette ikke er interessant (f.eks. hvis man lager basemap).
- [ ] **General:** This is a bit of a mess now, and it's highly customized for Globesar. I suggest that we make a simple pop-up that would "work for all" – (i.e. like the one we have on arkgis.org) – and that we have the extended version of it written as a plugin.
### LAYER MENU
- [ ] I find the magnifying glass a bit confusing. The plane was confusing too. I still think the four corner extend icon is the most logical/used one, something we got confirmed in one of our meetings with Frano.
### DESCRIPTION/LEGEND
- [ ] I never quite liked this. There is something off with it. Perhaps it's that the layers are mentioned above in the layer menu, and then they come again here. It might be an idea to look into a smoother way of doing this, and I don't see any point in proceeding to fix this feature on PDF screenshot until we have something a tad more solid.
- [ ] Have the option to disable meta information and opacity slider in the legend. Users should be able to have a clean legend box if they want to.
### FUTURE TOP PRIORITIES
- [ ] **Projections:** Having different projections in client. This is something that not many online providers are offering, and could be a selling point for us. 
- [ ] **Formats:** SOSI, etc. 
- [ ] **Chat:** Also a selling point. There is a lot of sockets needed. I think the chat would be a game changer to retention. Also very good to be able to do demo's when we can chat with users directly. (https://github.com/systemapic/wu/issues/231)
- [ ] **Half layer slider:** a vertical slider where layer only shows on one side, so that you can easily compare two layers.
