### ISSUE TITLE
More mature API

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#253]
### Make more robust API
- [x] #295: move all client-side api calls to single file (`Wu.Api`). mirror routes.js, socket.routes.js. 
- [x] #174: write tests for all endpoints 
- [x] #296: document each endpoint in routes.js, autogenerate documentation.
- [x] #300: clean up names and organize routes/endpoints more consistently
- [x] #317 standardize return messages, errors (always as JSON)
- [ ] create standardized specs for layer, file objects etc. see if existing specs can be used (eg. mapbox vtile)
- [x] add mocha to grunt, perhaps with pre-commit tests
