### ISSUE TITLE
Public projects

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#273]
#### Todo list
- [x] Create shareable link to a `public` project
- [x] Switch project being public on/off (button already there, must plug)
- [x] Give access to public project for users that are logged in but don't have the project on their list.
- [x] Implement usernames, see #274
- [x] project url like `beta.systemapic.com/username/project_slug`
- [x] clean up login flow (invite, login, hotlink, etc.)
- [ ] make it possible to access _all_ public projects? (might not want to share without giving out link; but some might want to make projects available to all. we can in that case list them! :+1: )
- [ ]  ...
### IMPORTANT
- [x] add attribution of norkart/mapbox/google on map
#### Background

Make it possible to have `public` projects, which can be shared and viewed immediately (no login). See https://github.com/systemapic/admin/issues/2 for non-tech details.
- must be able to access portal without being a user. 
- could be a `public` user, which means many people will be logged in to same "user" at the same time.
- hard to say what's the best way to do this, experiement.
- must work for all portals: ie. not just custom portal, but one with many users etc. 
- url needs to be something like `beta.systemapic.com/username/project_slug`
