### ISSUE TITLE
Stabilize uploads

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#420]
#### Issues:
- [ ] #409 upload non-geo files
- [x] #464 Fix `LATIN1` bug
- [ ] #391 add data directly to project with script 
- [x] #361 can only upload 5 files without reload
- [x] #375 interrupting upload leaves unstable state
- [ ] #267 zipped raster upload fails
- [x] #266 wrong chunk count
- [ ] #407 `.sosi` support
- [ ] #403 `.csv` support
- [x] https://github.com/systemapic/systemapic.js/issues/62 need refresh after upload
- [ ] add tests for many filetypes, for known errors, for raster, zipped raster, chunks
