### ISSUE TITLE
Version 1.6 Roadmap

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#493]
#### Scripts, tools
- [ ] Upload script, adding directly to project
- [x] Let user create logins for for other users (without sending them emails, etc.)
#### Raster handling
- [ ] Import raster: Create new `wu.dataset`, `wu.layer`, `pile.layer` (raster layers)
- [ ] Vectorize raster:  Create new `wu.dataset`, `wu.layer`, `pile.layer` (vector layers)
#### Datacubes - x, y and z for time
- [x] Create layer from multiple datasets (timeseries)
- [x] Add unique reference/family uuid to datasets, so that they can easily be grouped (and created layers from)
- [ ] Perhaps `wu.datacube` model, to keep track of datasets. Or just layer doing that job.
#### Export
- [ ] Request vector tiles from any dataset/cube
- [x] Request raster tiles (with cartocss) from any dataset (and cube, but not priority)
- [ ] Simplify geometry in vector tiles
- [ ] Masking polygons
#### Queries
- [ ] Query dataset for avg, min, max - whole set or clipped by mask
- [ ] Create "custom" queries, put in extension. Run query by looking up query-name specified in extension and running that, ie. pluggable queries.
- [ ] Create the custom query for snow-raster cubes.
#### Client-side
- [ ] [mapbox-gl.js](https://www.mapbox.com/mapbox-gl-js/api/)
- [ ] Separate page for these datacube layers (simple page, not portal)
  - simple because no time to implement mapbox-gl-js in the portal
  - must implement support in full portal later, but not by April 1st
  - timeseries play-button
  - login form to get `access_token`
- [ ] Styling of vector tiles. Range + color enough? 
- [ ] Multiple layers in one vector-tile set
- [ ] Dynamically change style (animation)
- [ ] Chart, query based on polygon mask ("nedbørsfelt")
