### ISSUE TITLE
Snø - tilbakemelding

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#529]
### todo
- [ ] cache layers
- [ ] pre-render layers
- [ ] redigere title/description of mask
- [x] gjøre alt norsk
- [x] standarder for `område`, `feltnavn`, `kraftverk`, `årlig tilsig`
- [x] bytte om overskriftene
- [ ] snø legend mangler (bug?)
- [ ] fargeskala for snø, viser ikke godt nok hvor det er < 100% snø
- [ ] forbedring av bakgrunnskart (@frano ser på nye mapbox kartlag)
- [ ] resizeable chart, automatisk stilt inn etter skjermstørrelse
- [ ] fix layer options pane
- [ ] polygon-valg?
- [ ] hydrologisk år
- [x] tooltip: "click to display mask" på hover
- [ ] bug: when changing project, tiles don't show 
- [ ] script for importing daily snow rasters (!!!)
### feedback

Eirik:  

> -Ser at det fortsatt mangler data etter 15 juni 2016.
> 
> -Overskriften på grafen «Hallingdal Snow Cover-2016» blir litt rar. Ser ut som denne er statisk, og ikke endres dersom man velger Rjukan. Dessuten er det blanding mellom norsk og engelsk. Foreslår: «Snødekningsgrad» som hovedoverskrift, Og så underoverskrift: «Nedbørsfelt: Hallingdalsvassdraget» , der man bytter ut med navnet på andre felt.
> 
> -Når jeg velger Rjukan er det mye fin info om areal og årlig tilsig i teksten.  Stemmer det at Mår er kraftverket. Slik info bør i såfall også være for Hallingdal.
> - 2016 –kurven for Rjukan ser rar ut (veldig sein og hurtig snøsmelting).
> - Jeg får ikke opp snøkartene i det hele tatt her. Hvor har de blitt av? Burde vært mulig å velge på layers…
> 
> Generelt: Går fortsatt litt tregt synes jeg. Spesielt å velge andre datoer. Det er heller ikke mulig å velge andre år som skal vises (Datoen med stor skrift og tekstlig  SCF vises bare for 2016.

Tom:  

> -          Inkonsistens mht bruk av navn.  Det må lages en standard for navnsettingen: område, feltnavn, kraftverk etc.
> -          Standard bør lages for tilleggsinformasjon.  Årlig tilsig er oppgitt for Mår mens feltet heter Rjukan og for Hallingdal er det ingen tilleggsinfo
> -          Legend for SCF mangler (nederst til venstre)
> -          Fargeskala for SCF er dårlig.  Slik det fremstår nå  er det stort sett enten bar mark eller 100% snø og gir ikke god nok informasjon.  I flere av områdene er det 1000% snø i grenseområdet mellom snø og bar mark og slik er det ikke øverst i Hallingdal.
> -          Bakgrunnskartet endrer seg ved zooming.  Det dukker plutselig opp en masse skyer.
> -          Det virker som vinduet for SCF (nedre del til høyre) har fast størrelse.  På en liten skjerm vil dette dekke mye av kartet.  Er det mulig å forminske dette vinduet?
> -          Blanding av engelsk og norsk er ikke noe problem, men virker kanskje litt uferdig.  Hvis dette må låses og ikke tilpasse kunden, bør vel engelsk brukes (for et internasjonalt marked?).  En del norske kraftselskaper er sære på bruk av norsk.
> -          Polygon-valget er ikke operativt ennå, men det er sannsynligvis ikke meningen foreløpig?
> -          Er det mulig å veksle til hydrologisk år.?  Hydrologer og mange andre like å se vinteren i sammenheng med start av grafen på barmark og at vinteren bygger seg opp og til slutt melter i samme diagram.
