### ISSUE TITLE
immediate todo

### ISSUE THREAD

**Issue by knutole** [systemapic/wu#533]
- [x] set up `localhost` for shah
- [x] open up docker images @ docker hub
- [x] clean out passwords from all repos
- [x] move all repo links to /mapic
- [ ] clean up `wms` branch, make some improvements for monday
- [x] clean up `analytics` branch for shah's first assignment https://github.com/systemapic/wu/issues/415
